In [1]:
from StackedAE import Convolution_Auto_Encoder as CAE
from StackedAE import Convolution_AE_Classification as CAC
import torch
import torch.nn
import os
import sys
import numpy as np
import json

sys.path.append(os.path.dirname(os.path.abspath(os.path.dirname(""))))
import commons
import utils
import audio_processing as ap

In [2]:
#model load from save path
config_path =  "/media/caijb/data_drive/autoencoder/log/kernel5/config.json"

#load paramters
with open(config_path, 'r') as f:
    data = f.read()
config = json.loads(data)
hps = utils.HParams(**config)

#load model & load saved model weight
checkpoint_path = utils.latest_checkpoint_path(hps.train.model_dir)

model = CAE(encoder_dim=hps.model.encoder_dim, hidden_1dim=hps.model.hidden_dim1,
    hidden_2dim=hps.model.hidden_dim2, kernel=hps.model.kernel)

utils.load_checkpoint(checkpoint_path, model)

/media/caijb/data_drive/autoencoder/log/kernel5/G_203.pth
INFO:root:Loaded checkpoint '/media/caijb/data_drive/autoencoder/log/kernel5/G_203.pth' (iteration 203)


(Convolution_Auto_Encoder(
   (encoder): Encoder(
     (conv2d_layer_1): Conv2d(1, 3, kernel_size=(5, 5), stride=(1, 1))
     (conv2d_layer_2): Conv2d(3, 5, kernel_size=(5, 5), stride=(1, 1))
     (relu): ReLU()
   )
   (decoder): Decoder(
     (Tconv2d_layer1): ConvTranspose2d(5, 3, kernel_size=(5, 5), stride=(1, 1))
     (Tconv2d_layer2): ConvTranspose2d(3, 1, kernel_size=(5, 5), stride=(1, 1))
     (relu): ReLU()
   )
 ),
 None,
 0.0001,
 203)

In [3]:
model.state_dict().keys()

odict_keys(['encoder.conv2d_layer_1.weight', 'encoder.conv2d_layer_1.bias', 'encoder.conv2d_layer_2.weight', 'encoder.conv2d_layer_2.bias', 'decoder.Tconv2d_layer1.weight', 'decoder.Tconv2d_layer1.bias', 'decoder.Tconv2d_layer2.weight', 'decoder.Tconv2d_layer2.bias'])

In [4]:
tensor= torch.randn(1,80,430)

In [5]:
encoder=model.get_vector(tensor)
encoder.size()

torch.Size([5, 72, 422])

In [6]:
classification_model = CAC(encoder_dim=hps.model.encoder_dim, hidden_1dim=hps.model.hidden_dim1,
    hidden_2dim=hps.model.hidden_dim2, kernel=hps.model.kernel, hps = hps)

In [7]:
classification_model.state_dict().keys()

odict_keys(['encoder.conv2d_layer_1.weight', 'encoder.conv2d_layer_1.bias', 'encoder.conv2d_layer_2.weight', 'encoder.conv2d_layer_2.bias', 'classification.conv1x1.weight', 'classification.conv1x1.bias', 'classification.linear1.weight', 'classification.linear1.bias', 'classification.linear2.weight', 'classification.linear2.bias'])

In [8]:
classification_model.encoder.conv2d_layer_1.weight

Parameter containing:
tensor([[[[-0.0990, -0.1630,  0.0887,  0.1558,  0.0999],
          [-0.1165, -0.0607,  0.0381, -0.1053, -0.0414],
          [ 0.1569, -0.1830,  0.0941,  0.0373,  0.1240],
          [-0.0495, -0.1071, -0.1234,  0.1242,  0.0520],
          [ 0.1945, -0.0309,  0.0649,  0.0143, -0.0539]]],


        [[[ 0.1584, -0.0675,  0.0900,  0.0943, -0.1044],
          [-0.0956, -0.0699, -0.1691, -0.1267,  0.1515],
          [ 0.0864, -0.0489, -0.0379,  0.0264,  0.0268],
          [ 0.0410, -0.1575,  0.1524,  0.0815,  0.0208],
          [ 0.0557,  0.0477, -0.0418,  0.0830,  0.0777]]],


        [[[-0.0221, -0.1223, -0.0940, -0.0227,  0.0494],
          [ 0.1191,  0.1469,  0.1449, -0.1497, -0.0680],
          [-0.0684, -0.0455,  0.0701, -0.1364,  0.1926],
          [-0.1175, -0.1825,  0.1542,  0.0147,  0.0329],
          [ 0.0985,  0.1286,  0.0511, -0.1165,  0.1313]]]], requires_grad=True)

In [9]:
model.encoder.conv2d_layer_1.weight

Parameter containing:
tensor([[[[-0.0257, -0.1003,  0.3286,  0.4681, -0.1894],
          [-0.1451,  0.1371, -0.1216,  0.4228, -0.1207],
          [ 0.0255, -0.0569, -0.0945, -0.0432, -0.1239],
          [ 0.1142, -0.1354,  0.0706,  0.0328,  0.0506],
          [ 0.1053,  0.2175,  0.0425, -0.0424, -0.0102]]],


        [[[ 0.0859,  0.1653,  0.2484,  0.2368, -0.0686],
          [ 0.0818,  0.1169, -0.1984, -0.1115, -0.0978],
          [-0.0162,  0.0448,  0.1337,  0.0938,  0.2012],
          [-0.0523,  0.0512, -0.1359, -0.1301, -0.0707],
          [-0.0996, -0.0348,  0.1467,  0.0944, -0.0671]]],


        [[[ 0.0376, -0.0479, -0.1037, -0.0086,  0.0558],
          [ 0.0264,  0.0793,  0.1925, -0.3262, -0.0777],
          [ 0.0345,  0.1169, -0.2020,  0.1778,  0.2321],
          [ 0.2132, -0.0024,  0.0219, -0.1180, -0.0346],
          [ 0.2287,  0.2257, -0.0916,  0.0153, -0.0708]]]], requires_grad=True)

In [10]:
classification_model.encoder=model.encoder

In [11]:
classification_model.encoder.conv2d_layer_1.weight

Parameter containing:
tensor([[[[-0.0257, -0.1003,  0.3286,  0.4681, -0.1894],
          [-0.1451,  0.1371, -0.1216,  0.4228, -0.1207],
          [ 0.0255, -0.0569, -0.0945, -0.0432, -0.1239],
          [ 0.1142, -0.1354,  0.0706,  0.0328,  0.0506],
          [ 0.1053,  0.2175,  0.0425, -0.0424, -0.0102]]],


        [[[ 0.0859,  0.1653,  0.2484,  0.2368, -0.0686],
          [ 0.0818,  0.1169, -0.1984, -0.1115, -0.0978],
          [-0.0162,  0.0448,  0.1337,  0.0938,  0.2012],
          [-0.0523,  0.0512, -0.1359, -0.1301, -0.0707],
          [-0.0996, -0.0348,  0.1467,  0.0944, -0.0671]]],


        [[[ 0.0376, -0.0479, -0.1037, -0.0086,  0.0558],
          [ 0.0264,  0.0793,  0.1925, -0.3262, -0.0777],
          [ 0.0345,  0.1169, -0.2020,  0.1778,  0.2321],
          [ 0.2132, -0.0024,  0.0219, -0.1180, -0.0346],
          [ 0.2287,  0.2257, -0.0916,  0.0153, -0.0708]]]], requires_grad=True)

In [13]:
for p in classification_model.encoder.parameters():
    p.requires_grad = False

In [16]:
classification_model.encoder.conv2d_layer_1.

AttributeError: 'Conv2d' object has no attribute 'requires_grad'

In [15]:
model.encoder.conv2d_layer_1.weight

Parameter containing:
tensor([[[[-0.0257, -0.1003,  0.3286,  0.4681, -0.1894],
          [-0.1451,  0.1371, -0.1216,  0.4228, -0.1207],
          [ 0.0255, -0.0569, -0.0945, -0.0432, -0.1239],
          [ 0.1142, -0.1354,  0.0706,  0.0328,  0.0506],
          [ 0.1053,  0.2175,  0.0425, -0.0424, -0.0102]]],


        [[[ 0.0859,  0.1653,  0.2484,  0.2368, -0.0686],
          [ 0.0818,  0.1169, -0.1984, -0.1115, -0.0978],
          [-0.0162,  0.0448,  0.1337,  0.0938,  0.2012],
          [-0.0523,  0.0512, -0.1359, -0.1301, -0.0707],
          [-0.0996, -0.0348,  0.1467,  0.0944, -0.0671]]],


        [[[ 0.0376, -0.0479, -0.1037, -0.0086,  0.0558],
          [ 0.0264,  0.0793,  0.1925, -0.3262, -0.0777],
          [ 0.0345,  0.1169, -0.2020,  0.1778,  0.2321],
          [ 0.2132, -0.0024,  0.0219, -0.1180, -0.0346],
          [ 0.2287,  0.2257, -0.0916,  0.0153, -0.0708]]]])